# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Project Information
site_name: Documentation
site_description: Data-Intensive Social Science Center Documentation
site_author: DISSC
site_url: https://DISSC.github.io/docs

# Repository
repo_name: docs
repo_url: https://github.com/DISSC-yale/docs
edit_uri: edit/main/docs/

# Important for correct viewing offline
use_directory_urls: false

theme:
  palette:
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto Serif
    code: Roboto Mono
  logo: assets/DISSC wordmark package/png/DISSC_ol_white.png
  name: material
  icon:
    edit: material/pencil
    view: material/eye

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.action.edit
    - navigation.instant
    - content.code.copy

extra:
  social:
    - icon: material/home-circle
      link: https://dissc.yale.edu
      name: DISSC home page
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/data-intensive-social-science-center-dissc-at-yale-university?trk=public_post-text
      name: LinkedIn

# Plugins
plugins:
  - search:
      lang:
        - en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 200%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# These extensions are chosen to be a superset of Pandocs Markdown.
# This way, I can write in Pandocs Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - md_in_html

nav:
  - Version Control:
      - accessing_yale_github_enterpise.md
      - git_basics.md
      - using_git.md
      - dvc_basics.md
      - using_dvc.md
  - High-Performance Computing:
      - hpc/ood.md
      - hpc/quick_start.md
